package com.TugasAkhir.DocIn.model;

public enum JabatanDokter {
    DOKTER_UMUM, SPESIALIS_ANAK, SPESIALIS_BEDAH, SPESIALIS_SARAF, SPESIALIS_JANTUNG, SPESIALIS_MATA, SPESIALIS_KULIT, SPESIALIS_PARU, SPESIALIS_GIGI,
    SPESIALIS_PENYAKIT_DALAM, SPESIALIS_FORENSIK
}
